apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-deploy
spec:
  selector:
    matchLabels:
      app: my-profile
  replicas: 3
  template:
    metadata:
      labels:
        app: my-profile
    spec:
      containers:
      - name: my-profile
        image: vguptag/abc_tech:latest
        ports:
        - containerPort: 8080
