apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-deploy
spec:
  selector:
    matchLabels:
      app: IGP2
  replicas: 3
  template:
    metadata:
      labels:
        app: IGP2
    spec:
      containers:
      - name: IGP2
        image: vguptag/abc_tech:latest
        ports:
        - containerPort: 8080
