---
- name: Deploy Docker Image to Kubernetes
  hosts: localhost
  tasks:
    - name: Create Kubernetes deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: my-app
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: my-app
            template:
              metadata:
                labels:
                  app: my-app
              spec:
                containers:
                - name: my-app
                  image: your-docker-image:latest
                  ports:
                  - containerPort: 80

    - name: Create Kubernetes service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: my-app-service
          spec:
            selector:
              app: my-app
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
            type: LoadBalancer
