---
- name: Install Podman on Amazon Linux
  hosts: local
  become: true
  tasks:
    - name: Update all packages
      dnf:
        name: '*'
        state: latest

    - name: Install required dependencies
      dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add EPEL repository
      dnf:
        name: epel-release
        state: present

    - name: Install Podman
      dnf:
        name: podman
        state: present
