---
- name: Install Docker on CentOS
  hosts: local
  become: true

  tasks:
    - name: Gather Facts
      ansible.builtin.setup:
    
    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install required dependencies
      ansible.builtin.dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
    
    - name: Add Docker repository
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: '0644'

    - name: Clear the YUM cache
      ansible.builtin.command:
        cmd: yum clean all

    - name: Clear the DNF cache
      ansible.builtin.command:
        cmd: dnf clean all

    - name: Install Docker
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started
