---
- name: Install Docker on Amazon Linux
  hosts: local
  become: true
  tasks:
    - name: Update all packages
      dnf:
        name: '*'
        state: latest

    - name: Install required dependencies
      dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add user to the docker group
      user:
        name: guptav-nl
        groups: docker
        append: true
